### ISSUE TITLE
End of command options -- is not respected in 2.0.1

### ISSUE THREAD

**Issue by AlexSkrypnyk** [ahoy-cli/ahoy#100]
Having ahoy.yml:
```
  up:
    usage: Build and start Docker containers.
    cmd: |
      docker-compose up -d "$@"
```

In 2.0.0:

`ahoy up -- --build` => OK

In 2.0.1
`ahoy up -- --build` => `unknown service --build` meaning that `-- --build` is passed literally instead of  just `--build`
