### ISSUE TITLE
Run commands then drop into a shell

### ISSUE THREAD

**Issue by frankcarey** [ahoy-cli/ahoy#21]
There may be times where you want to start a shell, but run some commands first (like set env variables or do some checks) . It looks like you can do that by using:

`bash --init-file <(echo "ls; pwd")`

Maybe we can add a `before:` setting on the commands that would do this automatically? 

See http://serverfault.com/questions/368054/run-an-interactive-bash-subshell-with-initial-commands-without-returning-to-the

**Comment by frankcarey** [comment]
It's now possible (as of today in v2) to do something more advanced like this by customizing the entrypoint. This might be an interesting way to add plugins.

**Comment by frankcarey** [comment]
I ended up using this feature today with entrypoint so that virtualenv python was activated on every call..
```
ahoyapi: v2
entrypoint: [bash, -init-file, .env/bin/activate, -c, '{{cmd}}', '{{name}}']
commands: ...
```

**Comment by q0rban** [comment]
In theory, since this is yml, could you do something like this with anchors?

```yml
ahoyapi: v2
python_entrypoint: &python_entrypoint
  - bash
  - "--init-file"
  - .env/bin/activate
  - "-i"
  - "-c"
  - '{{cmd}}'
  - '{{name}}'
commands:
  my-python-command:
    entrypoint: *python_entrypoint
    usage: ...
    cmd: ...
```
