### ISSUE TITLE
Fix the `init` command for v2

### ISSUE THREAD

**Issue by frankcarey** [ahoy-cli/ahoy#58]
Right now, `ahoy init` downloads a v1 ahoy file to start with. It should also contain much better examples, code comments, etc.. so that it's even easier to get started.

**Comment by AlexSkrypnyk** [comment]
This is fixed now.

https://raw.githubusercontent.com/ahoy-cli/ahoy/master/examples/examples.ahoy.yml

```
ahoyapi: v2
commands:
  vup:
    cmd: "vagrant up"
    usage: Start the vagrant box if one exists.
....
```
