### ISSUE TITLE
Add a complete sub-command example for v2

### ISSUE THREAD

**Issue by benjifisher** [ahoy-cli/ahoy#65]
I copied the example `.ahoy.yml` from the home page, ending with this:

```yaml
  subcommands:
      usage: List the commands from the imported config files.
      # These commands will be aggregated together with later files overriding earlier ones if they exist.
      imports:
        - ./some-file1.ahoy.yml
        - ./some-file2.ahoy.yml
        - ./some-file3.ahoy.yml
```

I then created `some-file1.ahoy.yml`:

```yaml
ahoyapi: v2
commands:
  foo:
    cmd: echo "file1 foo"
    usage: Test command for file1.
```

and two similar files. I must be doing something wrong:

```
$ ahoy
[fatal] Command [subcommands] has 'imports' set, but no commands were found. Check your yaml file.
```

I think a more complete example would help.

**Comment by benjifisher** [comment]
Oops, I had a typo. Fix the typo, no more error.

Still, an updated example would be helpful.

**Comment by frankcarey** [comment]
yeah, the examples are super out of date and really incomplete.. there are lots of patterns now across various implementers that would be good to generalize into examples here.

**Comment by AlexSkrypnyk** [comment]
Both README and Docs documentation seems correct.

<img width="917" height="591" alt="Image" src="https://github.com/user-attachments/assets/3c40dbea-06f3-4039-a277-2dd70a7d333f" />

<img width="703" height="306" alt="Image" src="https://github.com/user-attachments/assets/516c0018-8d71-46fd-afb7-c1ba9d21e8f7" />


This code (similar to the above) is used in multiple projects:

```yaml
  local:
    usage: Custom local commands. See `ahoy local help`.
    optional: true
    imports:
      - .ahoy.local.yml
```

I'm closing this as the documentation describes the usage of sub-commands correctly.
